import React,{useEffect,useState} from 'react';
import {Button,Card,FormField,SectionHeader,SelectInput,TextArea,TextInput} from '../AppUI';
import {apiPost,apiPut,getChecklists,getCustomers,getRentals,getStoredAuthUser,listVehicleOptions,type ChecklistResponse,type VehicleOption} from '../../services/api';
import {Customer,RentalContract} from '../../types';
import {InspectionEvidence,exteriorLabels,interiorLabels,tyreLabels,newEvidence,downloadRecord,preparePhoto} from './evidence';
import InspectionRecord from './InspectionRecord';
interface Draft{id?:string;checklistNumber:string;rentalId:string;vehicleId:string;customerName:string;customerPhone:string;rentalType:string;rentalStartDate:string;evidence:InspectionEvidence;completed?:boolean;}
const params=()=>new URLSearchParams(window.location.hash.split('?')[1]);
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
const fresh=():Draft=>({checklistNumber:'CHK-'+crypto.randomUUID(),rentalId:params().get('rental')||'',vehicleId:'',customerName:'',customerPhone:'',rentalType:params().get('type')||'PICKUP',rentalStartDate:today(),evidence:newEvidence()});
export default function InspectionWorkflow(){
 const key='fleet.inspection.'+(getStoredAuthUser()?.username||'')+'.'+(params().get('rental')||'general')+'.'+(params().get('type')||'PICKUP');
 const [draft,setDraft]=useState<Draft>(()=>{try{const s=localStorage.getItem(key);return s?JSON.parse(s):fresh();}catch{return fresh();}});
 const [rentals,setRentals]=useState<RentalContract[]>([]),[vehicles,setVehicles]=useState<VehicleOption[]>([]),[customers,setCustomers]=useState<Customer[]>([]),[records,setRecords]=useState<ChecklistResponse[]>([]);
 const [step,setStep]=useState(0),[busy,setBusy]=useState(false),[photoBusy,setPhotoBusy]=useState(false),[warning,setWarning]=useState<string|null>(null),[saved,setSaved]=useState(''),[viewing,setViewing]=useState<ChecklistResponse|null>(null);
 useEffect(()=>{Promise.all([getRentals(),listVehicleOptions(),getCustomers(),getChecklists()]).then(([r,v,c,h])=>{setRentals(r);setVehicles(v);setCustomers(c);setRecords(h);setDraft(d=>{const selected=r.find(r=>r.id===d.rentalId);if(!selected||d.vehicleId)return d;const customer=c.find(c=>c.id===selected.customerId);return{...d,vehicleId:selected.vehicleId,customerName:selected.customerName,customerPhone:customer?.phone||'',rentalStartDate:selected.pickupDateTime.slice(0,10),evidence:{...d.evidence,odometer:selected.odometerOut,fuelLevel:selected.fuelOut}};});}).catch(e=>setWarning(e.message));},[]);
 useEffect(()=>{try{localStorage.setItem(key,JSON.stringify(draft));setSaved(draft.completed?'Completed inspection saved':'Draft retained on this device');}catch{setSaved('Device storage is full. Save a server draft before leaving.');}},[draft,key]);
 const evidence=(next:Partial<InspectionEvidence>)=>setDraft(d=>({...d,evidence:{...d.evidence,...next,acknowledged:false}}));
 const selectRental=(id:string)=>{const r=rentals.find(r=>r.id===id),c=customers.find(c=>c.id===r?.customerId);setDraft(d=>({...d,rentalId:id,vehicleId:r?.vehicleId||'',customerName:r?.customerName||'',customerPhone:c?.phone||'',rentalStartDate:r?.pickupDateTime.slice(0,10)||d.rentalStartDate,evidence:{...d.evidence,odometer:r?.odometerOut||0,fuelLevel:r?.fuelOut||'Full',acknowledged:false}}));};
 const save=async(completed:boolean)=>{setWarning(null);if(!draft.vehicleId||!draft.customerName.trim()||!draft.customerPhone.trim()){setWarning('Choose a vehicle and enter the customer name and phone.');setStep(0);return;}setBusy(true);try{const payload={...draft,completed,rentalId:draft.rentalId||null,staffName:getStoredAuthUser()?.username||''};const id=draft.id?(await apiPut<ChecklistResponse>('/api/checklists/'+draft.id,payload)).id:await apiPost<string>('/api/checklists',payload);setDraft(d=>({...d,id,completed}));setRecords(await getChecklists());setSaved(completed?'Inspection completed and stored':'Draft saved to server');}catch(e){setWarning(e instanceof Error?e.message:'Save failed. Your draft is retained.');}finally{setBusy(false);}};
 const photos=async(files:FileList|null)=>{if(!files)return;if(draft.evidence.photos.length+files.length>12){setWarning('Up to 12 photos can be attached.');return;}setPhotoBusy(true);try{const items=[];for(const file of Array.from(files))items.push(await preparePhoto(file));evidence({photos:[...draft.evidence.photos,...items]});setWarning(null);}catch(e){setWarning(e instanceof Error?e.message:'Unable to read photo');}finally{setPhotoBusy(false);}};
 const open=(r:ChecklistResponse)=>{if(r.completed){setViewing(r);return;}if(!r.evidence){setWarning('This older record has no condition evidence. Start a new inspection.');return;}setDraft({id:r.id,checklistNumber:r.checklistNumber,rentalId:r.rentalId||'',vehicleId:r.vehicle?.id||'',customerName:r.customerName,customerPhone:r.customerPhone,rentalType:r.rentalType,rentalStartDate:r.rentalStartDate,evidence:r.evidence});setStep(0);};
 if(viewing)return <><Button variant="secondary" onClick={()=>setViewing(null)}>Back to inspections</Button><InspectionRecord record={viewing}/></>;
 return <div className="app-grid" style={{gap:20}}><SectionHeader title="Vehicle inspection" description="Record condition, attach evidence and review it with the customer." warning={warning}/><div role="status" aria-live="polite">{saved}</div>
 {draft.completed?<Card className="workflow-card"><h3>Inspection completed</h3><p>The saved evidence is protected from further changes.</p><div className="workflow-actions"><Button onClick={()=>{setDraft(fresh());setStep(0);}}>New inspection</Button><Button variant="secondary" onClick={()=>downloadRecord(draft,draft.checklistNumber)}>Download copy</Button>{draft.rentalId&&<a href={'#rentals?id='+draft.rentalId}>Return to rental</a>}</div></Card>:<>
 <div className="workflow-actions" aria-label="Inspection steps">{['Vehicle','Exterior','Interior and tyres','Review'].map((name,i)=><Button key={name} variant={i===step?'primary':'secondary'} aria-current={i===step?'step':undefined} onClick={()=>setStep(i)}>{i+1}. {name}</Button>)}</div>
 <Card className="workflow-card">{step===0&&<div className="workflow-grid"><FormField label="Rental"><SelectInput value={draft.rentalId} onChange={e=>selectRental(e.target.value)}><option value="">Standalone inspection</option>{rentals.filter(r=>r.status!=='Closed'||r.id===draft.rentalId).map(r=><option key={r.id} value={r.id}>{r.rentalNumber} — {r.customerName} — {r.vehiclePlate}</option>)}</SelectInput></FormField><FormField label="Vehicle"><SelectInput value={draft.vehicleId} disabled={!!draft.rentalId} onChange={e=>setDraft({...draft,vehicleId:e.target.value,evidence:{...draft.evidence,acknowledged:false}})}><option value="">Choose vehicle</option>{vehicles.map(v=><option key={v.id} value={v.id}>{v.label}</option>)}</SelectInput></FormField><FormField label="Inspection type"><SelectInput value={draft.rentalType} onChange={e=>setDraft({...draft,rentalType:e.target.value,evidence:{...draft.evidence,acknowledged:false}})}>{['PICKUP','RETURN','MAINTENANCE','DAMAGE'].map(t=><option key={t}>{t}</option>)}</SelectInput></FormField><FormField label="Customer name"><TextInput value={draft.customerName} onChange={e=>setDraft({...draft,customerName:e.target.value,evidence:{...draft.evidence,acknowledged:false}})}/></FormField><FormField label="Customer phone"><TextInput type="tel" value={draft.customerPhone} onChange={e=>setDraft({...draft,customerPhone:e.target.value})}/></FormField><FormField label="Odometer (km)"><TextInput type="number" min={0} value={draft.evidence.odometer} onChange={e=>evidence({odometer:Number(e.target.value)})}/></FormField><FormField label="Fuel"><SelectInput value={draft.evidence.fuelLevel} onChange={e=>evidence({fuelLevel:e.target.value})}>{['Full','3/4','1/2','1/4','Empty'].map(f=><option key={f}>{f}</option>)}</SelectInput></FormField></div>}
 {step===1&&<><h3>Exterior condition</h3><p>Inspect every point. Describe each abnormal condition.</p>{draft.evidence.exterior.map((p,i)=><div key={p.id} className="workflow-point"><strong>{exteriorLabels[i]}</strong><SelectInput aria-label={exteriorLabels[i]+' condition'} value={p.status} onChange={e=>evidence({exterior:draft.evidence.exterior.map(point=>point.id===p.id?{...point,status:e.target.value}:point)})}>{['Not Inspected','Normal','Abnormal','N/A'].map(s=><option key={s}>{s}</option>)}</SelectInput><TextInput aria-label={exteriorLabels[i]+' notes'} placeholder="Observation or damage description" value={p.notes} onChange={e=>evidence({exterior:draft.evidence.exterior.map(point=>point.id===p.id?{...point,notes:e.target.value}:point)})}/></div>)}</>}
 {step===2&&<><h3>Interior observations</h3><div className="workflow-grid">{Object.entries(interiorLabels).map(([k,label])=><div key={k}><FormField label={label}><TextArea placeholder="Record condition, including when normal" value={draft.evidence.interior[k]} onChange={e=>evidence({interior:{...draft.evidence.interior,[k]:e.target.value}})}/></FormField></div>)}</div><h3>Tyres</h3><div className="workflow-grid">{Object.entries(tyreLabels).map(([k,label])=><div key={k}><FormField label={label}><SelectInput value={draft.evidence.tyres[k]} onChange={e=>evidence({tyres:{...draft.evidence.tyres,[k]:e.target.value}})}>{['Not Inspected','Normal','Abnormal','N/A'].map(s=><option key={s}>{s}</option>)}</SelectInput></FormField></div>)}</div></>}
 {step===3&&<><h3>Review with {draft.customerName||'the customer'}</h3><p>{draft.evidence.odometer} km · Fuel {draft.evidence.fuelLevel} · {draft.evidence.exterior.filter(p=>p.status==='Abnormal').length} abnormal exterior points · {draft.evidence.photos.length} photos</p><ul>{draft.evidence.exterior.filter(p=>p.status!=='Normal').map(p=><li key={p.id}>{exteriorLabels[p.id-101]}: {p.status} — {p.notes}</li>)}</ul><p>Review the observations and photos together before acknowledging. Completed inspections are retained as a record.</p><FormField label="Customer full name for acknowledgement"><TextInput value={draft.evidence.acknowledgedBy} onChange={e=>evidence({acknowledgedBy:e.target.value})}/></FormField><label className="app-check-option"><input type="checkbox" checked={draft.evidence.acknowledged} onChange={e=>setDraft({...draft,evidence:{...draft.evidence,acknowledged:e.target.checked}})}/>I have reviewed the vehicle condition and acknowledge this inspection record.</label></>}</Card>
 <Card className="workflow-card"><h3>Photo evidence</h3><p>Up to 12 photos. Describe the location or damage in each photo.</p><input aria-label="Add inspection photos" type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={photoBusy||busy} onChange={e=>{photos(e.target.files);e.target.value='';}}/>{photoBusy&&<p role="status">Preparing photos…</p>}<div className="workflow-photos">{draft.evidence.photos.map((p,i)=><div key={i}><img src={p.data} alt={p.label}/><TextInput aria-label={'Photo '+(i+1)+' description'} value={p.label} maxLength={100} onChange={e=>evidence({photos:draft.evidence.photos.map((p,j)=>j===i?{...p,label:e.target.value}:p)})}/><Button variant="ghost" onClick={()=>evidence({photos:draft.evidence.photos.filter((_,j)=>j!==i)})}>Remove</Button></div>)}</div></Card>
 {warning&&<p role="alert" className="app-warning-text">{warning}</p>}<div className="workflow-actions"><Button variant="secondary" disabled={busy||photoBusy} onClick={()=>save(false)}>{busy?'Saving…':'Save server draft'}</Button>{step>0&&<Button variant="secondary" onClick={()=>setStep(step-1)}>Back</Button>}{step<3?<Button onClick={()=>setStep(step+1)}>Continue</Button>:<Button disabled={busy||photoBusy||!draft.evidence.acknowledged} onClick={()=>save(true)}>Complete inspection</Button>}</div></>}
 <Card className="workflow-card"><h3>Inspection history</h3>{records.filter(r=>!draft.rentalId||r.rentalId===draft.rentalId).slice().reverse().map(r=><div key={r.id} className="app-note-row"><span>{r.vehicle?.plateNumber} · {r.rentalType} · {r.completed?'Completed':'Draft'}</span><Button variant="secondary" onClick={()=>open(r)}>{r.completed?'View evidence':'Resume draft'}</Button></div>)}</Card></div>;
}

