import React,{useEffect,useState} from 'react';
import {apiGet,apiPost,type BookingRequest,type ChecklistResponse} from '../services/api';
import {Booking,Customer,Invoice,RatePlan,RentalContract,PricingBreakdown} from '../types';
import {Button,Card,FormField,SectionHeader,SelectInput,TextInput} from './AppUI';
import InspectionRecord from './Checklist/InspectionRecord';
import {downloadRecord} from './Checklist/evidence';
interface PortalData{customer:Customer;bookings:Booking[];rentals:RentalContract[];invoices:Invoice[];ratePlans:RatePlan[];}
interface Quote{pricing:PricingBreakdown;deposit:number;available:number;currency:string;}
export default function CustomerTrips(){
 const [data,setData]=useState<PortalData|null>(null),[records,setRecords]=useState<ChecklistResponse[]>([]),[selected,setSelected]=useState<ChecklistResponse|null>(null),[error,setError]=useState<string|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[quote,setQuote]=useState<Quote|null>(null);
 const [form,setForm]=useState<BookingRequest>({customerId:'self',pickupLocation:'HQ',dropoffLocation:'HQ',pickupDateTime:'',dropoffDateTime:'',vehicleClass:'Sedan',estimatedTotal:0,depositAmount:0,notes:''});
 const [currentPassword,setCurrentPassword]=useState(''),[newPassword,setNewPassword]=useState('');
 const load=async()=>{const [d,r]=await Promise.all([apiGet<PortalData>('/api/portal/me'),apiGet<ChecklistResponse[]>('/api/portal/inspections')]);setData(d);setRecords(r);};
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 const change=(next:Partial<BookingRequest>)=>{setForm({...form,...next});setQuote(null);};
 if(!data)return <p role="status">{error||'Loading your trips…'}</p>;
 return <div className="app-grid" style={{gap:20}}><SectionHeader title={'Welcome, '+data.customer.fullName} description="Book a vehicle, review your trips and keep a copy of your documents." warning={error}/>{message&&<p role="status">{message}</p>}
 <Card className="workflow-card"><h2>Plan your trip</h2><form className="workflow-grid" onSubmit={async e=>{e.preventDefault();setBusy(true);setError(null);try{if(!quote){setQuote(await apiPost<Quote>('/api/portal/quote',form));}else{await apiPost('/api/portal/bookings',{...form,estimatedTotal:quote.pricing.estimatedTotal,depositAmount:quote.deposit});setMessage('Your booking is confirmed and a vehicle is reserved. Bring your driving licence and identity document to pickup. The refundable deposit is collected by staff.');setQuote(null);await load();}}catch(e){setQuote(null);setError(e instanceof Error?e.message:'Booking failed');}finally{setBusy(false);}}}>
 <FormField label="Pickup"><TextInput required type="datetime-local" value={form.pickupDateTime} onChange={e=>change({pickupDateTime:e.target.value})}/></FormField><FormField label="Return"><TextInput required type="datetime-local" value={form.dropoffDateTime} onChange={e=>change({dropoffDateTime:e.target.value})}/></FormField><FormField label="Vehicle class"><SelectInput value={form.vehicleClass} onChange={e=>change({vehicleClass:e.target.value})}>{Array.from(new Set(data.ratePlans.map(p=>p.vehicleClass))).map(c=><option key={c}>{c}</option>)}</SelectInput></FormField><FormField label="Pickup location"><TextInput required value={form.pickupLocation} onChange={e=>change({pickupLocation:e.target.value})}/></FormField><FormField label="Return location"><TextInput required value={form.dropoffLocation} onChange={e=>change({dropoffLocation:e.target.value})}/></FormField><Button disabled={busy||!!quote&&!quote.available}>{busy?'Please wait…':quote?'Confirm booking':'Check availability and price'}</Button></form>{quote&&<div><h3>{quote.available} vehicles available</h3><p>{quote.pricing.rentalDays} days × {quote.currency} {quote.pricing.baseRate.toFixed(2)} · Tax {quote.pricing.taxTotal.toFixed(2)}</p><p><strong>Rental total: {quote.currency} {quote.pricing.estimatedTotal.toFixed(2)}</strong></p><p>Refundable deposit: {quote.currency} {quote.deposit.toFixed(2)} (separate from the rental price).</p></div>}</Card>
 <Card className="workflow-card"><h2>Your bookings</h2>{data.bookings.length===0?<p>Your upcoming trips will appear here after booking.</p>:data.bookings.map(b=><div key={b.id} className="app-note-row"><div><strong>{b.vehicleClass}</strong><p>{new Date(b.pickupDateTime).toLocaleString()} → {new Date(b.dropoffDateTime).toLocaleString()}</p><p>{b.pickupLocation} → {b.dropoffLocation} · {b.status}</p></div>{['Draft','Confirmed','Assigned'].includes(b.status)&&!data.rentals.some(r=>r.bookingId===b.id)&&<Button variant="secondary" disabled={busy} onClick={async()=>{if(!window.confirm('Cancel this booking?'))return;setBusy(true);try{await apiPost('/api/portal/bookings/'+b.id+'/cancel');await load();setMessage('Booking cancelled.');}catch(e){setError(e instanceof Error?e.message:'Unable to cancel');}finally{setBusy(false);}}}>Cancel booking</Button>}</div>)}</Card>
 <Card className="workflow-card"><h2>Invoices and inspection records</h2>{data.invoices.map(i=><div key={i.id} className="app-note-row"><div>{i.invoiceNumber} · {i.status}<ul>{i.lineItems.map(l=><li key={l.id}>{l.label}: ${l.amount.toFixed(2)}</li>)}</ul><p>Total ${i.total.toFixed(2)} · Outstanding ${i.balanceDue.toFixed(2)}</p></div><Button variant="secondary" onClick={()=>downloadRecord(i,i.invoiceNumber)}>Download invoice</Button></div>)}{records.map(r=><div key={r.id} className="app-note-row"><span>{r.vehicle?.plateNumber} · {r.rentalType}</span><Button variant="secondary" onClick={()=>setSelected(r)}>View inspection</Button></div>)}{!data.invoices.length&&!records.length&&<p>Your documents will appear after the rental is prepared.</p>}</Card>{selected&&<InspectionRecord record={selected}/>}
 <Card className="workflow-card"><h2>Change password</h2><form className="workflow-grid" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await apiPost('/api/users/change-password',{currentPassword,newPassword,confirmPassword:newPassword});setCurrentPassword('');setNewPassword('');setMessage('Password changed.');}catch(e){setError(e instanceof Error?e.message:'Unable to change password');}finally{setBusy(false);}}}><FormField label="Current password"><TextInput required type="password" autoComplete="current-password" value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)}/></FormField><FormField label="New password"><TextInput required type="password" minLength={10} maxLength={40} autoComplete="new-password" value={newPassword} onChange={e=>setNewPassword(e.target.value)}/></FormField><Button disabled={busy}>Update password</Button></form></Card></div>;
}
