import React,{useEffect,useState} from 'react';
import {getBookings,getRentals,getVehicleStats} from '../services/api';
import {Booking,RentalContract} from '../types';
import {Button,Card,SectionHeader,StatCard} from './AppUI';
export default function OperationsDashboard(){
 const [data,setData]=useState<{bookings:Booking[];rentals:RentalContract[];stats:Awaited<ReturnType<typeof getVehicleStats>>}|null>(null),[error,setError]=useState<string|null>(null),[loading,setLoading]=useState(true);
 const load=()=>{setLoading(true);Promise.all([getBookings(),getRentals(),getVehicleStats()]).then(([bookings,rentals,stats])=>{setData({bookings,rentals,stats});setError(null);}).catch(e=>setError(e.message)).finally(()=>setLoading(false));};
 useEffect(load,[]);
 const today=(value:string)=>new Date(value).toDateString()===new Date().toDateString();
 return <div className="app-grid" style={{gap:20}}><SectionHeader title="Today's operations" description="Pickups, returns and vehicles that need attention." warning={error} action={<Button variant="secondary" onClick={load} disabled={loading}>Refresh</Button>}/>{loading&&<p role="status">Loading current records…</p>}{error&&data&&<p>Showing previously loaded records. Refresh to check the latest state.</p>}{data&&<><div className="app-grid app-grid--stats"><StatCard label="Fleet" value={data.stats.totalVehicles}/><StatCard label="Available" value={data.stats.availableVehicles}/><StatCard label="On rent" value={data.stats.rentedVehicles}/><StatCard label="Maintenance" value={data.stats.maintenanceVehicles}/></div><div className="workflow-grid"><Card className="workflow-card"><h3>Today's pickups</h3>{data.bookings.filter(b=>today(b.pickupDateTime)&&['Confirmed','Assigned'].includes(b.status)).map(b=><p key={b.id}><a href="#bookings">{b.customerName} · {b.vehicleClass} · {b.status}</a></p>)}<a href="#bookings">Manage bookings</a></Card><Card className="workflow-card"><h3>Returns due and overdue</h3>{data.rentals.filter(r=>['Active','Overdue'].includes(r.status)&&(today(r.expectedReturnDateTime)||new Date(r.expectedReturnDateTime)<new Date())).map(r=><p key={r.id}><a href={'#rentals?id='+r.id}>{r.vehiclePlate} · {r.customerName}</a></p>)}<a href="#rentals">All rentals</a></Card><Card className="workflow-card"><h3>Unassigned bookings</h3><p>{data.bookings.filter(b=>b.status==='Confirmed'&&!b.assignedVehicleId).length} need a vehicle</p><a href="#bookings">Assign vehicles</a></Card></div><Card className="workflow-card"><h3>Start a handover</h3><p>Open a rental to see its inspections, deposit and next action.</p><div className="workflow-actions"><a href="#rentals">Open rentals</a><a href="#customers">Add a customer</a><a href="#vehicles">Manage fleet</a><a href="#exceptions">Resolve exceptions</a></div></Card></>}</div>;
}
