import React,{useEffect,useState} from 'react';
import {getRentalById,getChecklists,getInvoices,startRental,type ChecklistResponse} from '../services/api';
import {Invoice,RentalContract} from '../types';
import {Button,Card,SectionHeader} from './AppUI';
import InspectionRecord from './Checklist/InspectionRecord';
export default function RentalDetail(){
 const id=new URLSearchParams(window.location.hash.split('?')[1]).get('id')||'';
 const [r,setR]=useState<RentalContract|null>(null),[records,setRecords]=useState<ChecklistResponse[]>([]),[invoices,setInvoices]=useState<Invoice[]>([]),[error,setError]=useState<string|null>(null),[selected,setSelected]=useState<ChecklistResponse|null>(null),[busy,setBusy]=useState(false);
 const load=()=>Promise.all([getRentalById(id),getChecklists(),getInvoices()]).then(([r,c,i])=>{setR(r||null);setRecords(c.filter(c=>c.rentalId===id));setInvoices(i.filter(i=>i.rentalId===id));}).catch(e=>setError(e.message));
 useEffect(()=>{load();},[id]);
 if(!r)return <p role="status">{error||'Loading rental…'}</p>;
 return <div className="app-grid" style={{gap:20}}><a href="#rentals">All rentals</a><SectionHeader title={r.rentalNumber} description={r.customerName+' · '+r.vehiclePlate+' · '+r.status} warning={error}/><Card className="workflow-card"><div className="workflow-grid"><div><h3>Trip</h3><p>{new Date(r.pickupDateTime).toLocaleString()} → {new Date(r.expectedReturnDateTime).toLocaleString()}</p></div><div><h3>Deposit</h3><p>${r.depositAmount.toFixed(2)} · {r.depositStatus}</p></div><div><h3>Outstanding invoices</h3><p>${invoices.reduce((sum,i)=>sum+i.balanceDue,0).toFixed(2)}</p></div></div><div className="workflow-actions">{r.status==='Reserved'&&<><a className="app-button app-button--secondary" href={'#checklist?rental='+id+'&type=PICKUP'}>Pickup inspection</a><Button disabled={busy} onClick={async()=>{setBusy(true);try{await startRental(id);await load();setError(null);}catch(e){setError(e instanceof Error?e.message:'Handover failed');}finally{setBusy(false);}}}>Start handover</Button></>}{['Active','Overdue'].includes(r.status)&&<><a className="app-button app-button--secondary" href={'#checklist?rental='+id+'&type=RETURN'}>Return inspection</a><a href={'#returns?rental='+id}>Assess return charges</a></>}<a href="#payments">Payment records</a></div><p>Handover requires a verified customer, collected deposit and completed pickup inspection.</p></Card><Card className="workflow-card"><h3>Inspection timeline</h3>{records.length===0?<p>No inspections yet. Start with the pickup inspection.</p>:records.map(c=><div className="app-note-row" key={c.id}><span>{c.rentalType} · {c.completed?'Completed':'Draft'}</span><Button variant="secondary" onClick={()=>setSelected(c)}>View evidence</Button></div>)}</Card>{selected&&<InspectionRecord record={selected}/>}<Card className="workflow-card"><h3>Billing</h3>{invoices.map(i=><div key={i.id} className="app-note-row"><div>{i.invoiceNumber}<ul>{i.lineItems.map(l=><li key={l.id}>{l.label}: ${l.amount.toFixed(2)}</li>)}</ul></div><div>{i.status}<br/>Due ${i.balanceDue.toFixed(2)}</div></div>)}</Card></div>;
}
